spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/reg
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: utf-8


